#   Copyright (C) 2020  Shamit Som <shamitsom@gmail.com>
#
#   This program is free software: you can redistribute it and/or modify
#   it under the terms of the GNU Affero General Public License as published
#   by the Free Software Foundation, either version 3 of the License, or
#   (at your option) any later version.
#
#   This program is distributed in the hope that it will be useful,
#   but WITHOUT ANY WARRANTY; without even the implied warranty of
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#   GNU Affero General Public License for more details.
#
#   You should have received a copy of the GNU Affero General Public License
#   along with this program.  If not, see <https://www.gnu.org/licenses/>.

import logging
import wx

from ..controller import PyrrhicController

from .base import MainFrame as bMainFrame
from .PrefsDialog import PrefsDialog
from .wxutils import modal_dialog_ok

_logger = logging.getLogger(__name__)

class MainFrame(bMainFrame):
    def __init__(self, parent):
        super(MainFrame, self).__init__(parent)
        self._controller = PyrrhicController(self)

    def __del__(self):
    # need to override this function (auto-generated by wxFormBuilder)
    # to avoid exception being thrown on close due to AUI manager deletion
        pass

    def info_box(self, title, message):
        modal_dialog_ok(self, title, message, wx.ICON_INFORMATION)

    def warning_box(self, title, message):
        modal_dialog_ok(self, title, message, wx.ICON_WARNING)

    def error_box(self, title, message):
        modal_dialog_ok(self, title, message, wx.ICON_ERROR)

    def OnClose(self, event):
        self.m_mgr.UnInit()
        event.Skip()

    def OnOpenRom(self, event):
        if not self._controller.DefsValid:
            modal_dialog_ok(
                self,
                'No definitions loaded! Please ensure definition paths are correct',
                'No Definitions Loaded',
                wx.ICON_WARNING
            )
            return

        dlg = wx.FileDialog(self,
            'Open ROM File',
            wildcard='Binary ROM Image (*.hex; *.bin)|*.hex;*.bin|All Files|*.*',
            style=wx.FD_OPEN | wx.FD_FILE_MUST_EXIST | wx.FD_MULTIPLE
        )
        result = dlg.ShowModal()

        if result == wx.ID_OK:
            fpaths = dlg.GetPaths()

            for fpath in fpaths:
                # TODO: sanity check files here?
                self._controller.open_rom(fpath)

    def OnPreferences(self, event):
        dlg = PrefsDialog(self, self._controller.Preferences)
        dlg.ShowModal()
        dlg.Destroy()

    @property
    def Controller(self):
        return self._controller